### ISSUE TITLE
from torch._C import * Import Error

### ISSUE THREAD

**Issue by SuchitReddi** [SuchitReddi/AIR-ASVspoof#3]
Terminal Input:
python train.py --add_loss ocsoftmax -o ./models1028/ocsoftmax/train --gpu 1

Terminal Output:
Traceback (most recent call last):
File "train.py", line 5, in
from resnet import setup_seed, ResNet
File "D:\Programming\Python\Python\AIR-ASVspoof\resnet.py", line 1, in
import torch
File "D:\Programming\Python\Python\venv\lib\site-packages\torch_init_.py", line 79,
in <module>
from torch._C import *
ImportError: DLL load failed: The specified procedure could not be found.

Comments: The same repeats even for --gpu 0. Tried reinstalling torch version 1.1.0 with and without GPU.

For additional information, the same code run on python terminal gave the following output:

D:\Programming\Python\Python\venv\Scripts\python.exe C:/Users/Suchit/AppData/Roaming/JetBrains/IntelliJIdea2022.2/plugins/python/helpers/pydev/pydevconsole.py --mode=client --host=127.0.0.1 --port=62758 
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['D:\\Programming\\Python\\Python'])
PyDev console: starting.
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
runfile('D:\\Programming\\Python\\Python\\AIR-ASVspoof-Suchit\\train.py', wdir='D:\\Programming\\Python\\Python\\AIR-ASVspoof-Suchit')
Traceback (most recent call last):
  File "C:\Users\Suchit\AppData\Local\Programs\Python\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\Suchit\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\Suchit\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Programming\Python\Python\AIR-ASVspoof-Suchit\train.py", line 5, in <module>
    from resnet import setup_seed, ResNet
  File "C:\Users\Suchit\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Programming\Python\Python\AIR-ASVspoof-Suchit\resnet.py", line 1, in <module>
    import torch
  File "C:\Users\Suchit\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Programming\Python\Python\venv\lib\site-packages\torch\__init__.py", line 79, in <module>
    from torch._C import *
  File "C:\Users\Suchit\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by SuchitReddi** [comment]
Refer this link to find the main resolved issue: https://github.com/yzyouzhang/AIR-ASVspoof/issues/36
